name: build_and_test

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "**"
      - "!main"
      
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
        
      - name: Download node modules
        run: npm install
      - name: Build client
        run: npm run build:prod
      - name: Lint client
        run: npm run lint
      - name: Run tests
        run: npm run tests
